version: '3.8'

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  open-webui-custom:
    build:
      context: .  # корень вашего проекта с изменениями
      dockerfile: Dockerfile.custom
    container_name: open-webui-custom
    volumes:
      - webui-data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"  # ваш фронтенд на 3000
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=ваш_секрет
    restart: unless-stopped

volumes:
  ollama: {}
  webui-data: {}